export const ELECTION_STYLE_ALIASES: Record<string, string> = {
  RESULTS_HUB: 'RESULTS_BAR',
  SPLIT_BAR_LEFT: 'VERSUS_PANEL',
  COUNTDOWN_TOP: 'COUNTDOWN_BANNER',
  LEAKS_FULL: 'BREAKING_PANEL',
  STATEMENT_FULL: 'QUOTE_PANEL',
  LIVE_TRANSITION: 'VERSUS_PANEL',
  STUDIO_BACKGROUND: 'SIDEBAR_TOWER',
  VOTER_TURNOUT: 'TURNOUT_STRIP',
};

export const resolveElectionStyle = (style: string) => {
  if (!style) return 'RESULTS_BAR';
  return ELECTION_STYLE_ALIASES[style] || style;
};

export const ELECTION_SOUND_OPTIONS = [
  'RESULTS_STING',
  'QUOTE_SWEEP',
  'VERSUS_IMPACT',
  'SIDEBAR_CHIME',
  'DATA_PULSE',
  'COUNTDOWN_TICK',
  'BREAKING_WHOOSH',
  'SOFT_FADE',
];

export const ELECTION_SOUND_IN_DEFAULTS: Record<string, string> = {
  RESULTS_BAR: 'RESULTS_STING',
  QUOTE_PANEL: 'QUOTE_SWEEP',
  VERSUS_PANEL: 'VERSUS_IMPACT',
  SIDEBAR_TOWER: 'SIDEBAR_CHIME',
  TURNOUT_STRIP: 'DATA_PULSE',
  COUNTDOWN_BANNER: 'COUNTDOWN_TICK',
  BREAKING_PANEL: 'BREAKING_WHOOSH',
};

export const ELECTION_SOUND_OUT_DEFAULTS: Record<string, string> = {
  RESULTS_BAR: 'SOFT_FADE',
  QUOTE_PANEL: 'SOFT_FADE',
  VERSUS_PANEL: 'SOFT_FADE',
  SIDEBAR_TOWER: 'SOFT_FADE',
  TURNOUT_STRIP: 'SOFT_FADE',
  COUNTDOWN_BANNER: 'SOFT_FADE',
  BREAKING_PANEL: 'SOFT_FADE',
};
