import { OverlayType, OverlayField, OverlayConfig } from '../../types';


// ─── حقول مشتركة لجميع قوالب المونديال ─────────────────────────────────────

const mondialCommonFields: OverlayField[] = [
  { id: 'channelName', label: 'اسم القناة', type: 'text', value: 'REO LIVE' },
  { id: 'mondialTheme', label: 'ثيم المونديال', type: 'select', value: 'MUNDIAL_MAIN', options: [
    { value: 'MUNDIAL_MAIN', label: '🌍 المونديال الرئيسي' },
    { value: 'MUNDIAL_NIGHT', label: '🌙 ليلة المباراة' },
    { value: 'MUNDIAL_GOLD', label: '🏆 الذهبي / النجوم' },
    { value: 'IRAQ_PRIDE', label: '🇮🇶 فخر العراق' },
    { value: 'TACTICAL_DARK', label: '🎯 تكتيك داكن' },
    { value: 'CLEAN_BROADCAST', label: '📡 بث نظيف' },
  ]},
  { id: 'scale', label: 'حجم القالب', type: 'range', value: 1.0, min: 0.5, max: 2.0, step: 0.05 },
  { id: 'positionY', label: 'إزاحة عمودية (Y)', type: 'range', value: 0, min: -700, max: 700, step: 10 },
  { id: 'positionX', label: 'إزاحة أفقية (X)', type: 'range', value: 0, min: -1200, max: 1200, step: 10 },
  { id: 'transitionIn', label: 'انتقال الظهور', type: 'select', value: 'STADIUM_SWEEP', options: [
    { value: 'STADIUM_SWEEP', label: 'كشف الملعب' },
    { value: 'SPOTLIGHT_POP', label: 'بروجكتور' },
    { value: 'LOWER_THIRD_WIPE', label: 'مسح جانبي' },
    { value: 'DATA_RUSH', label: 'دفق بيانات' },
    { value: 'DEFAULT', label: 'افتراضي' },
  ]},
  { id: 'transitionOut', label: 'انتقال الإخفاء', type: 'select', value: 'STADIUM_SWEEP_OUT', options: [
    { value: 'STADIUM_SWEEP_OUT', label: 'كشف الملعب عكسي' },
    { value: 'BROADCAST_OUT', label: 'بث خروج' },
    { value: 'SOFT_FADE', label: 'تلاشي ناعم' },
  ]},
  { id: 'soundEnabled', label: 'تفعيل الصوت', type: 'boolean', value: true },
  { id: 'soundVolume', label: 'مستوى الصوت', type: 'range', value: 0.75, min: 0, max: 2, step: 0.05 },
];

// ─── حقول بيانات المباراة (نظام dataMode الموحد) ─────────────────────────────

const mondialMatchDataFields: OverlayField[] = [
  { id: 'dataMode', label: 'مصدر بيانات المباراة', type: 'select', value: 'DEMO', options: [
    { value: 'CLOUD_BRIDGE', label: '☁️ جسر REO السحابي — Google Cloud' },
    { value: 'BRIDGE', label: '🔌 جسر محلي — localhost:3005' },
    { value: 'PASTE_JSON', label: '📋 JSON يدوي / ملف مستورد' },
    { value: 'DEMO', label: '🎮 بيانات تجريبية' },
  ]},
  { id: 'bridgeApiUrl', label: 'رابط API جسر البيانات', type: 'text', value: '/api/reo-match?action=match' },
  { id: 'manualJson', label: 'JSON بيانات المباراة (يدوي)', type: 'textarea', value: '' },
  { id: 'pollIntervalSec', label: 'تحديث من الجسر كل (ثانية)', type: 'range', value: 30, min: 10, max: 120, step: 5 },
  // بيانات يدوية (تُستخدم في DEMO + PASTE_JSON كـ fallback)
  { id: 'competition', label: 'اسم البطولة', type: 'text', value: 'FIFA World Cup 2026 · Group Stage' },
  { id: 'homeTeam', label: 'الفريق المضيف', type: 'text', value: 'العراق' },
  { id: 'awayTeam', label: 'الفريق الضيف', type: 'text', value: 'الأرجنتين' },
  { id: 'homeShort', label: 'اختصار المضيف', type: 'text', value: 'IRQ' },
  { id: 'awayShort', label: 'اختصار الضيف', type: 'text', value: 'ARG' },
  { id: 'homeScore', label: 'نتيجة المضيف', type: 'number', value: 1 },
  { id: 'awayScore', label: 'نتيجة الضيف', type: 'number', value: 0 },
  { id: 'minute', label: 'الدقيقة', type: 'text', value: '67' },
  { id: 'period', label: 'الشوط', type: 'text', value: 'الشوط الثاني' },
  { id: 'matchStatus', label: 'حالة المباراة', type: 'select', value: 'LIVE', options: [
    { value: 'PRE', label: 'قبل المباراة' },
    { value: 'LIVE', label: 'مباشر' },
    { value: 'HT', label: 'استراحة' },
    { value: 'FT', label: 'انتهت' },
    { value: 'AET', label: 'انتهت بعد الوقت الإضافي' },
    { value: 'PEN', label: 'ركلات الترجيح' },
  ]},
  { id: 'homeLogo', label: 'شعار المضيف (رابط)', type: 'image', value: '' },
  { id: 'awayLogo', label: 'شعار الضيف (رابط)', type: 'image', value: '' },
  { id: 'sceneImage', label: 'صورة خلفية المباراة / الجماهير', type: 'image', value: '' },
  { id: 'homeColor', label: 'لون المضيف', type: 'color', value: '#007A3D' },
  { id: 'awayColor', label: 'لون الضيف', type: 'color', value: '#74ACDF' },
  { id: 'eventsJson', label: 'أحداث المباراة JSON', type: 'textarea', value: JSON.stringify([
    { minute: 23, type: 'goal', player: 'أيمن حسين', team: 'home' },
  ]) },
];

// ─── مجموعة 1: البث المباشر ──────────────────────────────────────────────────

export const MONDIAL_LIVE_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-scoreboard-full',
    templateId: 'template-mondial-scoreboard-full',
    name: 'مونديال 2026 — لوحة النتيجة الكاملة',
    type: OverlayType.MONDIAL_LIVE,
    isVisible: false,
    templateIcon: 'WC26',
    templateAccent: '#E63946',
    templateGroup: 'MONDIAL_2026_LIVE',
    templateDescription: 'لوحة نتيجة احترافية لمباريات كأس العالم 2026 مع الأحداث والشعارات وبث مباشر.',
    theme: { primaryColor: '#E63946', secondaryColor: '#023E8A', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'scoreboard' },
      ...mondialMatchDataFields,
    ],
  },
  {
    id: 'template-mondial-scorebug',
    templateId: 'template-mondial-scorebug',
    name: 'مونديال 2026 — شريط النتيجة المدمج',
    type: OverlayType.MONDIAL_LIVE,
    isVisible: false,
    templateIcon: 'BUG',
    templateAccent: '#00B4D8',
    templateGroup: 'MONDIAL_2026_LIVE',
    templateDescription: 'شريط نتيجة مدمج لا يحجب البث المباشر، مع تحديث لحظي من الجسر.',
    theme: { primaryColor: '#00B4D8', secondaryColor: '#023E8A', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'scorebug' },
      { id: 'scorebugPosition', label: 'موقع الشريط', type: 'select', value: 'TOP_RIGHT', options: [
        { value: 'TOP_RIGHT', label: 'أعلى يمين' },
        { value: 'TOP_LEFT', label: 'أعلى يسار' },
        { value: 'TOP_CENTER', label: 'أعلى وسط' },
        { value: 'BOTTOM_LEFT', label: 'أسفل يسار' },
      ]},
      { id: 'competitionShort', label: 'اختصار البطولة', type: 'text', value: 'WC26' },
      ...mondialMatchDataFields,
    ],
  },
  {
    id: 'template-mondial-var-alert',
    templateId: 'template-mondial-var-alert',
    name: 'مونديال 2026 — تنبيه حكم الفيديو',
    type: OverlayType.MONDIAL_LIVE,
    isVisible: false,
    templateIcon: 'VAR',
    templateAccent: '#F59E0B',
    templateGroup: 'MONDIAL_2026_LIVE',
    templateDescription: 'تنبيه بصري قوي لقرارات VAR والأهداف والبطاقات الحمراء والركلات الجزاء.',
    theme: { primaryColor: '#F59E0B', secondaryColor: '#000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'var_alert' },
      { id: 'varAlertType', label: 'نوع التنبيه', type: 'select', value: 'VAR', options: [
        { value: 'VAR', label: '⬛ VAR Review' },
        { value: 'GOAL', label: '⚽ GOAL!' },
        { value: 'RED_CARD', label: '🟥 Red Card' },
        { value: 'PENALTY', label: '🟠 Penalty' },
      ]},
      { id: 'varMessage', label: 'رسالة التنبيه', type: 'text', value: 'مراجعة هدف محتمل' },
      { id: 'varPosition', label: 'موقع التنبيه', type: 'select', value: 'CENTER', options: [
        { value: 'CENTER', label: 'المركز' },
        { value: 'TOP', label: 'الأعلى' },
        { value: 'BOTTOM', label: 'الأسفل' },
      ]},
    ],
  },
  {
    id: 'template-mondial-match-preview',
    templateId: 'template-mondial-match-preview',
    name: 'مونديال 2026 — إعلان موعد المباراة',
    type: OverlayType.MONDIAL_LIVE,
    isVisible: false,
    templateIcon: 'PRV',
    templateAccent: '#F5B800',
    templateGroup: 'MONDIAL_2026_LIVE',
    templateDescription: 'عرض إعلان مواجهة اليوم مع الترتيب العالمي، التوقيت، وتشكيل المجموعة.',
    theme: { primaryColor: '#F5B800', secondaryColor: '#06071a', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'match_preview' },
      { id: 'matchStage', label: 'المرحلة / المجموعة', type: 'text', value: 'المرحلة الجماعية · المجموعة A' },
      { id: 'groupBadge', label: 'شارة الجولة', type: 'text', value: 'المجموعة A · الجولة 3' },
      { id: 'matchDate', label: 'تاريخ المباراة', type: 'text', value: 'الإثنين 15 يونيو 2026' },
      { id: 'matchTime', label: 'توقيت المباراة', type: 'text', value: '21:00' },
      { id: 'matchTimeLabel', label: 'تسمية التوقيت', type: 'text', value: 'بتوقيت العراق' },
      { id: 'matchVenue', label: 'الملعب والمدينة', type: 'text', value: 'يونيون بنك ستاديوم · لوس أنجلوس' },
      { id: 'homeCode', label: 'رمز المضيف', type: 'text', value: 'IQ' },
      { id: 'homeName', label: 'اسم المضيف', type: 'text', value: 'العراق' },
      { id: 'homeRank', label: 'الترتيب العالمي (مضيف)', type: 'text', value: '#89' },
      { id: 'homeW', label: 'فوز (مضيف)', type: 'number', value: 2 },
      { id: 'homeD', label: 'تعادل (مضيف)', type: 'number', value: 1 },
      { id: 'homeL', label: 'خسارة (مضيف)', type: 'number', value: 0 },
      { id: 'awayCode', label: 'رمز الضيف', type: 'text', value: 'FR' },
      { id: 'awayName', label: 'اسم الضيف', type: 'text', value: 'فرنسا' },
      { id: 'awayRank', label: 'الترتيب العالمي (ضيف)', type: 'text', value: '#2' },
      { id: 'sceneImage', label: 'صورة المواجهة / الملعب', type: 'image', value: '' },
      { id: 'awayW', label: 'فوز (ضيف)', type: 'number', value: 1 },
      { id: 'awayD', label: 'تعادل (ضيف)', type: 'number', value: 1 },
      { id: 'awayL', label: 'خسارة (ضيف)', type: 'number', value: 1 },
      { id: 'ticker', label: 'شريط الأخبار للمباراة', type: 'textarea', value: '⚽ العراق يواجه فرنسا في المباراة الحاسمة · الفوز يضمن التأهل للدور الـ16 · 🏟️ يونيون بنك ستاديوم 70,000 مقعد' },
      { id: 'showStandings', label: 'عرض الترتيب الجانبي؟', type: 'boolean', value: false },
      { id: 'standingsJson', label: 'جدول الترتيب الجانبي JSON', type: 'textarea', value: JSON.stringify([
        { code: 'IQ', name: 'العراق', p: 2, pts: 4 },
        { code: 'FR', name: 'فرنسا',  p: 2, pts: 4 },
        { code: 'SN', name: 'السنغال',p: 2, pts: 1 },
        { code: 'NO', name: 'النرويج',p: 2, pts: 0 },
      ]) },
    ],
  },
  {
    id: 'template-mondial-lineup',
    templateId: 'template-mondial-lineup',
    name: 'مونديال 2026 — تشكيلة المباراة',
    type: OverlayType.MONDIAL_LIVE,
    isVisible: false,
    templateIcon: 'LNP',
    templateAccent: '#007A3D',
    templateGroup: 'MONDIAL_2026_LIVE',
    templateDescription: 'عرض تشكيلة الفريق الأساسية والاحتياطية على الملعب التكتيكي.',
    theme: { primaryColor: '#007A3D', secondaryColor: '#06071a', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'lineup' },
      { id: 'code', label: 'رمز الدولة', type: 'text', value: 'IQ' },
      { id: 'teamName', label: 'اسم المنتخب', type: 'text', value: 'منتخب العراق' },
      { id: 'formation', label: 'التشكيلة', type: 'text', value: '4-3-3' },
      { id: 'coach', label: 'المدرب', type: 'text', value: 'خيسوس كاساس' },
      { id: 'color', label: 'لون التشكيلة', type: 'color', value: '#007A3D' },
      { id: 'playersJson', label: 'تشكيلة اللاعبين JSON', type: 'textarea', value: JSON.stringify([
        { num: 1, name: 'جلال حسن', pos: 'GK', x: 8, y: 50 },
        { num: 3, name: 'حسين علي', pos: 'DF', x: 28, y: 15 },
        { num: 4, name: 'سعد ناطق', pos: 'DF', x: 25, y: 38 },
        { num: 6, name: 'علي عدنان', pos: 'DF', x: 25, y: 62 },
        { num: 15, name: 'ضرغام إسماعيل', pos: 'DF', x: 28, y: 85 },
        { num: 8, name: 'إبراهيم بايش', pos: 'MF', x: 50, y: 20 },
        { num: 16, name: 'أمير العماري', pos: 'MF', x: 45, y: 50 },
        { num: 11, name: 'زيدان إقبال', pos: 'MF', x: 50, y: 80 },
        { num: 17, name: 'علي جاسم', pos: 'FW', x: 75, y: 18 },
        { num: 9, name: 'أيمن حسين', pos: 'FW', x: 82, y: 50 },
        { num: 10, name: 'مهند علي', pos: 'FW', x: 75, y: 82 }
      ]) },
    ],
  },
  {
    id: 'template-mondial-match-result',
    templateId: 'template-mondial-match-result',
    name: 'مونديال 2026 — نتيجة المباراة الكبيرة',
    type: OverlayType.MONDIAL_LIVE,
    isVisible: false,
    templateIcon: 'FT',
    templateAccent: '#E63946',
    templateGroup: 'MONDIAL_2026_LIVE',
    templateDescription: 'عرض نتيجة المباراة النهائية (FT) مع قائمة الهدافين والتوقيت والتفاصيل.',
    theme: { primaryColor: '#E63946', secondaryColor: '#06071a', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'match_result' },
      { id: 'homeCode', label: 'رمز المضيف', type: 'text', value: 'IQ' },
      { id: 'homeTeam', label: 'اسم المضيف', type: 'text', value: 'العراق' },
      { id: 'homeScore', label: 'نتيجة المضيف', type: 'number', value: 2 },
      { id: 'homeColor', label: 'لون المضيف', type: 'color', value: '#007A3D' },
      { id: 'awayCode', label: 'رمز الضيف', type: 'text', value: 'FR' },
      { id: 'awayTeam', label: 'اسم الضيف', type: 'text', value: 'فرنسا' },
      { id: 'awayScore', label: 'نتيجة الضيف', type: 'number', value: 1 },
      { id: 'awayColor', label: 'لون الضيف', type: 'color', value: '#003189' },
      { id: 'sceneImage', label: 'صورة المباراة / الاحتفال', type: 'image', value: '' },
      { id: 'stage', label: 'المرحلة / المجموعة', type: 'text', value: 'المجموعة A · الجولة 3' },
      { id: 'venue', label: 'الملعب والمدينة', type: 'text', value: 'يونيون بنك ستاديوم · لوس أنجلوس' },
      { id: 'homeGoalsJson', label: 'أهداف المضيف JSON', type: 'textarea', value: JSON.stringify([
        { player: 'أيمن حسين', min: '23' },
        { player: 'زيدان إقبال', min: '78' }
      ]) },
      { id: 'awayGoalsJson', label: 'أهداف الضيف JSON', type: 'textarea', value: JSON.stringify([
        { player: 'Mbappé', min: '45' }
      ]) },
    ],
  },
];

// ─── مجموعة 2: الإحصائيات ────────────────────────────────────────────────────

export const MONDIAL_STATS_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-match-stats',
    templateId: 'template-mondial-match-stats',
    name: 'مونديال 2026 — إحصائيات المباراة',
    type: OverlayType.MONDIAL_STATS,
    isVisible: false,
    templateIcon: '📊',
    templateAccent: '#3b82f6',
    templateGroup: 'MONDIAL_2026_STATS',
    templateDescription: 'مقارنة إحصائيات المباراة الكاملة مع بث مباشر من الجسر أو إدخال يدوي.',
    theme: { primaryColor: '#3b82f6', secondaryColor: '#1e293b', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'match_stats' },
      ...mondialMatchDataFields,
      // حقول الإحصائيات اليدوية
      { id: 'statPossessionHome', label: 'استحواذ المضيف %', type: 'range', value: 48, min: 0, max: 100, step: 1 },
      { id: 'statPossessionAway', label: 'استحواذ الضيف %', type: 'range', value: 52, min: 0, max: 100, step: 1 },
      { id: 'statShotsHome', label: 'تسديدات المضيف', type: 'number', value: 8 },
      { id: 'statShotsAway', label: 'تسديدات الضيف', type: 'number', value: 14 },
      { id: 'statOnTargetHome', label: 'على المرمى (مضيف)', type: 'number', value: 4 },
      { id: 'statOnTargetAway', label: 'على المرمى (ضيف)', type: 'number', value: 7 },
      { id: 'statCornersHome', label: 'ركنيات المضيف', type: 'number', value: 3 },
      { id: 'statCornersAway', label: 'ركنيات الضيف', type: 'number', value: 6 },
      { id: 'statFoulsHome', label: 'مخالفات المضيف', type: 'number', value: 12 },
      { id: 'statFoulsAway', label: 'مخالفات الضيف', type: 'number', value: 9 },
      { id: 'statYellowHome', label: 'إنذارات المضيف', type: 'number', value: 2 },
      { id: 'statYellowAway', label: 'إنذارات الضيف', type: 'number', value: 1 },
      { id: 'statPassHome', label: 'دقة التمرير المضيف %', type: 'range', value: 78, min: 0, max: 100, step: 1 },
      { id: 'statPassAway', label: 'دقة التمرير الضيف %', type: 'range', value: 88, min: 0, max: 100, step: 1 },
    ],
  },
];

// ─── مجموعة 3: النتائج والجداول ──────────────────────────────────────────────

const mondialBroadcastMotionFields: OverlayField[] = [
  { id: 'scale', label: 'Template scale', type: 'range', value: 1.0, min: 0.5, max: 2.0, step: 0.05 },
  { id: 'positionY', label: 'Position Y', type: 'range', value: 0, min: -700, max: 700, step: 10 },
  { id: 'positionX', label: 'Position X', type: 'range', value: 0, min: -1200, max: 1200, step: 10 },
  { id: 'broadcastMotion', label: 'Internal broadcast animation', type: 'boolean', value: true },
  { id: 'transitionSpeedMs', label: 'Transition speed (ms)', type: 'range', value: 860, min: 360, max: 1500, step: 10 },
  { id: 'transitionIntensity', label: 'Transition intensity', type: 'range', value: 1, min: 0.2, max: 1.8, step: 0.05 },
  { id: 'mondialMotionPreset', label: 'Motion + SFX preset', type: 'select', value: 'reference_stinger', options: [
    { value: 'reference_stinger', label: 'Reference stinger - geometric sweep + glitch SFX' },
    { value: 'scorebug_snap', label: 'Scorebug snap - fast TV score reveal' },
    { value: 'group_wall_rush', label: 'Group wall rush - data board reveal' },
    { value: 'story_glitch', label: 'Story glitch - social vertical reveal' },
    { value: 'custom', label: 'Custom/manual fields below' },
  ]},
  { id: 'transitionIn', label: 'IN transition', type: 'select', value: 'MONDIAL_STINGER', options: [
    { value: 'MONDIAL_STINGER', label: 'Mondial reference stinger' },
    { value: 'STADIUM_SWEEP', label: 'Stadium sweep' },
    { value: 'DATA_RUSH', label: 'Data rush' },
    { value: 'SPOTLIGHT_POP', label: 'Spotlight pop' },
    { value: 'LOWER_THIRD_WIPE', label: 'Side wipe' },
    { value: 'GLASS_SWEEP', label: 'Glass sweep' },
    { value: 'DEFAULT', label: 'Default' },
  ]},
  { id: 'transitionOut', label: 'OUT transition', type: 'select', value: 'MONDIAL_STINGER_OUT', options: [
    { value: 'MONDIAL_STINGER_OUT', label: 'Mondial reference stinger out' },
    { value: 'STADIUM_SWEEP_OUT', label: 'Stadium sweep out' },
    { value: 'DATA_RUSH_OUT', label: 'Data rush out' },
    { value: 'SPOTLIGHT_POP_OUT', label: 'Spotlight pop out' },
    { value: 'LOWER_THIRD_WIPE_OUT', label: 'Side wipe out' },
    { value: 'BROADCAST_FADE_OUT', label: 'Broadcast fade out' },
    { value: 'DEFAULT', label: 'Default' },
  ]},
  { id: 'soundEnabled', label: 'SFX enabled', type: 'boolean', value: true },
  { id: 'soundVolume', label: 'SFX volume', type: 'range', value: 0.85, min: 0, max: 2, step: 0.05 },
  { id: 'soundInStyle', label: 'SFX in', type: 'select', value: 'GLITCH_TRANSITION', options: [
    { value: 'DEFAULT', label: 'Default by template' },
    { value: 'STADIUM_WHOOSH', label: 'Stadium whoosh' },
    { value: 'TROPHY_FANFARE', label: 'Trophy fanfare' },
    { value: 'GLITCH_TRANSITION', label: 'Glitch transition' },
    { value: 'DATA_SLAM', label: 'Data slam' },
  ]},
  { id: 'soundOutStyle', label: 'SFX out', type: 'select', value: 'DIGITAL_SWEEP', options: [
    { value: 'DEFAULT', label: 'Default by template' },
    { value: 'BROADCAST_OUT', label: 'Broadcast out' },
    { value: 'DIGITAL_SWEEP', label: 'Digital sweep' },
    { value: 'SOFT_FADE', label: 'Soft fade' },
    { value: 'LUXURY_OUT', label: 'Luxury out' },
    { value: 'HARD_CUT', label: 'Hard cut' },
  ]},
  { id: 'audioUpdateCue', label: 'Data update SFX', type: 'select', value: 'DIGITAL_SWEEP', options: [
    { value: 'DATA_TICK', label: 'Data tick' },
    { value: 'SCOREBUG_SNAP', label: 'Score snap' },
    { value: 'GLITCH_TRANSITION', label: 'Glitch transition' },
    { value: 'DIGITAL_SWEEP', label: 'Digital sweep' },
  ]},
  { id: 'duckSfx', label: 'Duck SFX under voice', type: 'boolean', value: true },
];

const mondialBroadcastPresentationFields: OverlayField[] = [
  { id: 'channelName', label: 'Channel name', type: 'text', value: 'REO SHOW' },
  { id: 'broadcastStyle', label: 'Broadcast style', type: 'select', value: 'spectrum', options: [
    { value: 'spectrum', label: 'Spectrum - World Cup color system' },
    { value: 'stadium', label: 'Stadium - TV match graphics' },
    { value: 'signal', label: 'Signal - international broadcast data' },
    { value: 'neon_arc', label: 'Neon arc - black reference pack arcs' },
    { value: 'score_red', label: 'Score red - full-time scoreboard energy' },
    { value: 'clean_grid', label: 'Clean grid - final draw board' },
  ]},
  { id: 'broadcastPalette', label: 'Theme palette', type: 'select', value: 'global', options: [
    { value: 'global', label: 'Global black / blue / neon' },
    { value: 'reo', label: 'REO red / green / yellow' },
    { value: 'midnight', label: 'Midnight purple / cyan' },
    { value: 'electric', label: 'Electric cyan / lime / magenta' },
    { value: 'trophy', label: 'Trophy gold / black' },
    { value: 'score_red', label: 'Scoreboard red / white' },
    { value: 'social_green', label: 'Social green / blue' },
  ]},
  ...mondialBroadcastMotionFields,
];

const mondialWorldCupDataFields: OverlayField[] = [
  { id: 'dataMode', label: 'World Cup data source', type: 'select', value: 'CLOUD_BRIDGE', options: [
    { value: 'CLOUD_BRIDGE', label: 'FotMob through REO API' },
    { value: 'BRIDGE', label: 'Custom bridge URL' },
    { value: 'PASTE_JSON', label: 'Manual JSON' },
    { value: 'DEMO', label: 'Demo fallback' },
  ]},
  { id: 'bridgeApiUrl', label: 'World Cup API URL', type: 'text', value: '/api/reo-match?action=world-cup' },
  { id: 'manualJson', label: 'Manual World Cup JSON', type: 'textarea', value: '' },
  { id: 'pollIntervalSec', label: 'Refresh seconds', type: 'range', value: 75, min: 15, max: 300, step: 15 },
];

const mondialMatchSelectionFields: OverlayField[] = [
  { id: 'matchPickMode', label: 'Match selector', type: 'select', value: 'next', options: [
    { value: 'next', label: 'Next live/scheduled match' },
    { value: 'latest', label: 'Latest full-time match' },
    { value: 'featured', label: 'Match by index' },
  ]},
  { id: 'featuredMatchIndex', label: 'Featured match index', type: 'number', value: 1, min: 1, max: 104, step: 1 },
  { id: 'fixturesJson', label: 'Fixtures JSON fallback', type: 'textarea', value: '[]' },
];

export const MONDIAL_BROADCAST_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-group-wall',
    templateId: 'template-mondial-group-wall',
    name: 'Mondial 2026 - Full Groups Wall',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'A-L',
    templateAccent: '#0ce8cf',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'A full 12-group World Cup broadcast wall with flags, standings and selectable international TV styles.',
    theme: { primaryColor: '#2457ff', secondaryColor: '#0ce8cf', backgroundColor: '#050505', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'mondialVariant', label: 'Variant', type: 'hidden', value: 'group_wall' },
      ...mondialBroadcastPresentationFields,
      { id: 'groupWallLayout', label: 'Groups layout', type: 'select', value: '4x3', options: [
        { value: '4x3', label: '4 columns x 3 rows' },
        { value: '3x4', label: '3 columns x 4 rows' },
      ]},
      { id: 'groupWallTitle', label: 'Screen title', type: 'text', value: 'WORLD CUP 2026 GROUPS' },
      { id: 'groupWallSubtitle', label: 'Kicker', type: 'text', value: '48 TEAM - 12 GROUP - REO SHOW' },
      { id: 'showGroupStats', label: 'Show played and points', type: 'boolean', value: true },
      { id: 'groupsJson', label: 'Groups JSON fallback', type: 'textarea', value: '[]' },
      ...mondialWorldCupDataFields,
    ],
  },
  {
    id: 'template-mondial-all-flags-wall',
    templateId: 'template-mondial-all-flags-wall',
    name: 'Mondial 2026 - All Flags Identity Wall',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'FLAG',
    templateAccent: '#b6ff00',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'A reference-pack inspired all-flags identity wall with grouped national flags, neon shadows and TV stinger motion.',
    theme: { primaryColor: '#b6ff00', secondaryColor: '#0ce8cf', backgroundColor: '#050505', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'mondialVariant', label: 'Variant', type: 'hidden', value: 'flag_wall' },
      ...mondialBroadcastPresentationFields,
      { id: 'identityTitle', label: 'Screen title', type: 'text', value: 'ALL FLAGS IN 10 STYLES' },
      { id: 'identitySubtitle', label: 'Kicker', type: 'text', value: '48 NATIONAL TEAMS - WORLD CUP 2026' },
      { id: 'identityColumns', label: 'Flag grid columns', type: 'select', value: '8', options: [
        { value: '6', label: '6 columns - larger flags' },
        { value: '8', label: '8 columns - balanced wall' },
        { value: '12', label: '12 columns - dense TV wall' },
      ]},
      { id: 'identityLimit', label: 'Teams to show', type: 'number', value: 48, min: 12, max: 48, step: 1 },
      { id: 'showIdentityGroups', label: 'Show group tags', type: 'boolean', value: true },
      { id: 'groupsJson', label: 'Groups JSON fallback', type: 'textarea', value: '[]' },
      ...mondialWorldCupDataFields,
    ],
  },
  {
    id: 'template-mondial-team-code-wall',
    templateId: 'template-mondial-team-code-wall',
    name: 'Mondial 2026 - Stylized Team Codes',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'CODE',
    templateAccent: '#ff2f9f',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'A stylized team-code wall inspired by the distorted national-name reference frames, using chromatic broadcast text.',
    theme: { primaryColor: '#ff2f9f', secondaryColor: '#2457ff', backgroundColor: '#050505', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'mondialVariant', label: 'Variant', type: 'hidden', value: 'team_code_wall' },
      ...mondialBroadcastPresentationFields,
      { id: 'identityTitle', label: 'Screen title', type: 'text', value: 'STYLIZED TEAM NAMES' },
      { id: 'identitySubtitle', label: 'Kicker', type: 'text', value: 'FLAGS - CODES - BROADCAST IDENTITY' },
      { id: 'identityColumns', label: 'Code columns', type: 'select', value: '4', options: [
        { value: '3', label: '3 columns - oversized text' },
        { value: '4', label: '4 columns - reference wall' },
        { value: '6', label: '6 columns - compact text' },
      ]},
      { id: 'identityLimit', label: 'Teams to show', type: 'number', value: 48, min: 12, max: 48, step: 1 },
      { id: 'showIdentityGroups', label: 'Show group badges', type: 'boolean', value: true },
      { id: 'groupsJson', label: 'Groups JSON fallback', type: 'textarea', value: '[]' },
      ...mondialWorldCupDataFields,
    ],
  },
  {
    id: 'template-mondial-match-announcement',
    templateId: 'template-mondial-match-announcement',
    name: 'Mondial 2026 - Match Announcement',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'VS',
    templateAccent: '#b6ff00',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'International TV-style match announcement card with flags, date, venue and selectable broadcast style.',
    theme: { primaryColor: '#b6ff00', secondaryColor: '#0ce8cf', backgroundColor: '#050505', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'mondialVariant', label: 'Variant', type: 'hidden', value: 'match_announcement' },
      ...mondialBroadcastPresentationFields,
      { id: 'matchCardTitle', label: 'Screen title', type: 'text', value: 'MATCH DAY' },
      { id: 'matchCardSubtitle', label: 'Kicker', type: 'text', value: 'WORLD CUP 2026' },
      ...mondialMatchSelectionFields,
      ...mondialWorldCupDataFields,
    ],
  },
  {
    id: 'template-mondial-full-time-broadcast',
    templateId: 'template-mondial-full-time-broadcast',
    name: 'Mondial 2026 - Full-Time Broadcast',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'FT',
    templateAccent: '#ff1738',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'Full-time result card using the latest finished FotMob fixture with bold broadcast score treatment.',
    theme: { primaryColor: '#ff1738', secondaryColor: '#2457ff', backgroundColor: '#050505', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'mondialVariant', label: 'Variant', type: 'hidden', value: 'full_time' },
      ...mondialBroadcastPresentationFields,
      { id: 'fullTimeTitle', label: 'Screen title', type: 'text', value: 'FULL-TIME' },
      { id: 'matchCardSubtitle', label: 'Kicker', type: 'text', value: 'WORLD CUP 2026' },
      { ...mondialMatchSelectionFields[0], value: 'latest' },
      ...mondialMatchSelectionFields.slice(1),
      ...mondialWorldCupDataFields,
    ],
  },
  {
    id: 'template-mondial-social-story',
    templateId: 'template-mondial-social-story',
    name: 'Mondial 2026 - Vertical Story Card',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: '9:16',
    templateAccent: '#2457ff',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'Centered 9:16 social story card for match day or score posts, styled from the World Cup reference pack.',
    theme: { primaryColor: '#2457ff', secondaryColor: '#ff2f9f', backgroundColor: '#050505', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'mondialVariant', label: 'Variant', type: 'hidden', value: 'social_story' },
      ...mondialBroadcastPresentationFields,
      { id: 'storyTitle', label: 'Story title', type: 'text', value: 'MATCH DAY' },
      ...mondialMatchSelectionFields,
      ...mondialWorldCupDataFields,
    ],
  },
  {
    id: 'template-mondial-knockout-bracket',
    templateId: 'template-mondial-knockout-bracket',
    name: 'Mondial 2026 - Road To The Final',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'R32',
    templateAccent: '#ff2f9f',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'Round-of-32 knockout map through the final and third-place match, populated from FotMob when available.',
    theme: { primaryColor: '#ff2f9f', secondaryColor: '#b6ff00', backgroundColor: '#050505', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'mondialVariant', label: 'Variant', type: 'hidden', value: 'knockout_bracket' },
      ...mondialBroadcastPresentationFields,
      { id: 'bracketTitle', label: 'Screen title', type: 'text', value: 'ROAD TO THE FINAL' },
      { id: 'bracketSubtitle', label: 'Kicker', type: 'text', value: 'ROUND OF 32 - WORLD CUP 2026' },
      { id: 'roundsJson', label: 'Knockout JSON fallback', type: 'textarea', value: '[]' },
      ...mondialWorldCupDataFields,
    ],
  },
];

export const MONDIAL_RESULTS_TEMPLATES: OverlayConfig[] = [
  ...MONDIAL_BROADCAST_TEMPLATES,
  {
    id: 'template-mondial-group-table',
    templateId: 'template-mondial-group-table',
    name: 'مونديال 2026 — جدول المجموعة',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'GRP',
    templateAccent: '#22c55e',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'جدول ترتيب المجموعة مع إبراز المتأهلين وبيانات كاملة.',
    theme: { primaryColor: '#22c55e', secondaryColor: '#1e293b', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'group_table' },
      { id: 'groupName', label: 'اسم المجموعة', type: 'select', value: 'A', options: ['A','B','C','D','E','F','G','H','I','J','K','L'].map(v => ({ value: v, label: `المجموعة ${v}` })) },
      { id: 'qualifiedSpots', label: 'عدد المتأهلين', type: 'number', value: 2 },
      { id: 'competition', label: 'البطولة', type: 'text', value: 'FIFA World Cup 2026' },
      { id: 'groupTeamsJson', label: 'فرق المجموعة JSON', type: 'textarea', value: JSON.stringify([
        { name: 'Iraq', nameAr: 'العراق', flag: '🇮🇶', played: 2, won: 1, drawn: 1, lost: 0, gf: 2, ga: 1, pts: 4 },
        { name: 'Argentina', nameAr: 'الأرجنتين', flag: '🇦🇷', played: 2, won: 1, drawn: 1, lost: 0, gf: 3, ga: 1, pts: 4 },
        { name: 'Australia', nameAr: 'أستراليا', flag: '🇦🇺', played: 2, won: 1, drawn: 0, lost: 1, gf: 2, ga: 3, pts: 3 },
        { name: 'China', nameAr: 'الصين', flag: '🇨🇳', played: 2, won: 0, drawn: 0, lost: 2, gf: 0, ga: 2, pts: 0 },
      ]) },
      ...mondialMatchDataFields.slice(0, 4), // dataMode فقط
    ],
  },
  {
    id: 'template-mondial-match-report',
    templateId: 'template-mondial-match-report',
    name: 'مونديال 2026 — تقرير المباراة',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'RPT',
    templateAccent: '#10b981',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'تقرير ما بعد المباراة مع رجل المباراة والتقييم والملخص.',
    theme: { primaryColor: '#10b981', secondaryColor: '#1e293b', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'match_report' },
      ...mondialMatchDataFields,
      { id: 'reportText', label: 'نص تقرير المباراة', type: 'textarea', value: 'انتهت المباراة بفوز تاريخي للمنتخب العراقي.' },
      { id: 'momName', label: 'رجل المباراة', type: 'text', value: 'أيمن حسين' },
      { id: 'momRating', label: 'تقييم رجل المباراة (0-10)', type: 'range', value: 8.7, min: 0, max: 10, step: 0.1 },
    ],
  },
];

// ─── مجموعة 4: التصريحات ─────────────────────────────────────────────────────

export const MONDIAL_QUOTES_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-quote',
    templateId: 'template-mondial-quote',
    name: 'مونديال 2026 — بطاقة تصريح',
    type: OverlayType.MONDIAL_QUOTES,
    isVisible: false,
    templateIcon: 'QTE',
    templateAccent: '#a855f7',
    templateGroup: 'MONDIAL_2026_QUOTES',
    templateDescription: 'بطاقة اقتباس احترافية لتصريحات المدربين والنجوم في مونديال 2026.',
    theme: { primaryColor: '#a855f7', secondaryColor: '#1e293b', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'quote' },
      { id: 'quoteCategory', label: 'تصنيف الاقتباس', type: 'select', value: 'تصريح بارز', options: [
        { value: 'تصريح بارز', label: 'تصريح بارز' },
        { value: 'مؤتمر صحفي', label: 'مؤتمر صحفي' },
        { value: 'ما بعد المباراة', label: 'ما بعد المباراة' },
        { value: 'قبل المباراة', label: 'قبل المباراة' },
        { value: 'رأي الخبير', label: 'رأي الخبير' },
      ]},
      { id: 'quoteText', label: 'نص الاقتباس', type: 'textarea', value: 'هذا الفريق يستحق أكثر من هذا — سنعود أقوى في المباراة القادمة.' },
      { id: 'authorName', label: 'اسم صاحب الاقتباس', type: 'text', value: 'ديدييه ديشان' },
      { id: 'authorTeam', label: 'الفريق / الصفة', type: 'text', value: 'مدرب منتخب فرنسا' },
      { id: 'authorFlag', label: 'إيموجي العلم', type: 'text', value: '🇫🇷' },
      { id: 'authorImage', label: 'صورة صاحب الاقتباس', type: 'image', value: '' },
    ],
  },
];

// ─── مجموعة 5: التحليل ───────────────────────────────────────────────────────

export const MONDIAL_ANALYSIS_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-analysis',
    templateId: 'template-mondial-analysis',
    name: 'مونديال 2026 — استوديو التحليل',
    type: OverlayType.MONDIAL_ANALYSIS,
    isVisible: false,
    templateIcon: 'ANA',
    templateAccent: '#22d3ee',
    templateGroup: 'MONDIAL_2026_ANALYSIS',
    templateDescription: 'لوحة تحليل تكتيكي مع الاستحواذ والمواجهات الحاسمة وقراءة المباراة.',
    theme: { primaryColor: '#22d3ee', secondaryColor: '#0f172a', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'analysis_board' },
      ...mondialMatchDataFields,
      { id: 'homeFormation', label: 'تشكيلة المضيف', type: 'text', value: '4-3-3' },
      { id: 'awayFormation', label: 'تشكيلة الضيف', type: 'text', value: '4-2-3-1' },
      { id: 'analysisText', label: 'قراءة المباراة', type: 'textarea', value: 'يلعب المنتخب بتشكيلة 4-3-3 معتمداً على الضغط العالي والهجمات المرتدة السريعة.' },
      { id: 'keyBattle1', label: 'المواجهة الحاسمة 1', type: 'text', value: 'أيمن حسين vs Romero' },
      { id: 'keyBattle2', label: 'المواجهة الحاسمة 2', type: 'text', value: 'وسط الميدان vs De Paul' },
      { id: 'possession', label: 'استحواذ المضيف %', type: 'range', value: 48, min: 0, max: 100, step: 1 },
      { id: 'possessionAway', label: 'استحواذ الضيف %', type: 'range', value: 52, min: 0, max: 100, step: 1 },
    ],
  },
];

// ─── مجموعة 6: النجوم والتوقعات ──────────────────────────────────────────────

export const MONDIAL_STARS_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-golden-boot',
    templateId: 'template-mondial-golden-boot',
    name: 'مونديال 2026 — سباق الحذاء الذهبي',
    type: OverlayType.MONDIAL_STARS,
    isVisible: false,
    templateIcon: '👟',
    templateAccent: '#FFD700',
    templateGroup: 'MONDIAL_2026_STARS',
    templateDescription: 'ترتيب هدافي المونديال مع الأعلام والأندية، مناسب للبث المستمر.',
    theme: { primaryColor: '#FFD700', secondaryColor: '#1a1000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'golden_boot' },
      { id: 'scorersJson', label: 'قائمة الهدافين JSON', type: 'textarea', value: JSON.stringify([
        { name: 'Kylian Mbappé', nameAr: 'كيليان مبابي', team: 'France', flag: '🇫🇷', goals: 5 },
        { name: 'Erling Haaland', nameAr: 'إيرلينغ هالاند', team: 'Norway', flag: '🇳🇴', goals: 4 },
        { name: 'أيمن حسين', nameAr: 'أيمن حسين', team: 'Iraq', flag: '🇮🇶', goals: 3 },
      ]) },
      ...mondialMatchDataFields.slice(0, 4),
    ],
  },
  {
    id: 'template-mondial-prediction',
    templateId: 'template-mondial-prediction',
    name: 'مونديال 2026 — توقعات المباراة',
    type: OverlayType.MONDIAL_STARS,
    isVisible: false,
    templateIcon: 'PRD',
    templateAccent: '#7c5cff',
    templateGroup: 'MONDIAL_2026_STARS',
    templateDescription: 'مقياس التوقعات لنتيجة مباراة بنسب فوز ذكية ومصدر البيانات.',
    theme: { primaryColor: '#7c5cff', secondaryColor: '#1e293b', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'prediction' },
      { id: 'predictionTitle', label: 'عنوان التوقع', type: 'text', value: 'من سيفوز؟' },
      { id: 'homeTeam', label: 'الفريق الأول', type: 'text', value: 'العراق' },
      { id: 'awayTeam', label: 'الفريق الثاني', type: 'text', value: 'الأرجنتين' },
      { id: 'homeWinPct', label: 'نسبة فوز الأول %', type: 'range', value: 35, min: 0, max: 100, step: 1 },
      { id: 'drawPct', label: 'نسبة التعادل %', type: 'range', value: 25, min: 0, max: 100, step: 1 },
      { id: 'awayWinPct', label: 'نسبة فوز الثاني %', type: 'range', value: 40, min: 0, max: 100, step: 1 },
      { id: 'homeColor', label: 'لون الأول', type: 'color', value: '#007A3D' },
      { id: 'awayColor', label: 'لون الثاني', type: 'color', value: '#74ACDF' },
      { id: 'predictionSource', label: 'مصدر التوقع', type: 'text', value: 'REO Prediction Engine · AI' },
    ],
  },
  {
    id: 'template-mondial-player-spotlight',
    templateId: 'template-mondial-player-spotlight',
    name: 'مونديال 2026 — تسليط الضوء على نجم',
    type: OverlayType.MONDIAL_STARS,
    isVisible: false,
    templateIcon: '⭐',
    templateAccent: '#FFD700',
    templateGroup: 'MONDIAL_2026_STARS',
    templateDescription: 'عرض بطاقة تقييم وإحصائيات لاعب محدد في المباراة بشكل مفصل.',
    theme: { primaryColor: '#FFD700', secondaryColor: '#10142a', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'player_spotlight' },
      { id: 'name', label: 'اسم اللاعب', type: 'text', value: 'أيمن حسين' },
      { id: 'code', label: 'رمز الدولة', type: 'text', value: 'IQ' },
      { id: 'position', label: 'المركز', type: 'text', value: 'مهاجم صريح' },
      { id: 'team', label: 'المنتخب', type: 'text', value: 'منتخب العراق' },
      { id: 'rating', label: 'التقييم', type: 'text', value: '9.1' },
      { id: 'playerImage', label: 'صورة اللاعب', type: 'image', value: '' },
      { id: 'statsJson', label: 'إحصائيات اللاعب JSON', type: 'textarea', value: JSON.stringify([
        { label: 'الأهداف المسجلة', value: '2' },
        { label: 'التسديدات على المرمى', value: '3 / 4' },
        { label: 'صناعة الفرص المحققة', value: '1' },
        { label: 'الفوز بالالتحامات الهوائية', value: '85%' },
        { label: 'دقة التمريرات', value: '79%' },
        { label: 'المسافة المقطوعة', value: '9.4 كم' }
      ]) },
    ],
  },
];

// ─── مجموعة 7: الأخبار والشرائط ──────────────────────────────────────────────

export const MONDIAL_NEWS_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-ticker',
    templateId: 'template-mondial-ticker',
    name: 'مونديال 2026 — شريط أخبار',
    type: OverlayType.MONDIAL_RESULTS,
    isVisible: false,
    templateIcon: 'TICK',
    templateAccent: '#E63946',
    templateGroup: 'MONDIAL_2026_RESULTS',
    templateDescription: 'شريط أخبار متدحرج لتحديثات مونديال 2026 — سريع وبارز ومضيء.',
    theme: { primaryColor: '#E63946', secondaryColor: '#0a0a14', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'ticker' },
      { id: 'tickerLabel', label: 'عنوان الشريط', type: 'text', value: '🏆 أخبار المونديال' },
      { id: 'tickerContent', label: 'نص الشريط', type: 'textarea', value: 'أيمن حسين يقود العراق في مونديال 2026 — الفريق الأول عربياً يصل ثمن النهائي' },
      { id: 'scrollSpeed', label: 'سرعة التمرير', type: 'range', value: 20, min: 5, max: 60, step: 1 },
    ],
  },
  {
    id: 'template-mondial-lower-third',
    templateId: 'template-mondial-lower-third',
    name: 'مونديال 2026 — شريط تعريف',
    type: OverlayType.MONDIAL_QUOTES,
    isVisible: false,
    templateIcon: 'LOW3',
    templateAccent: '#22d3ee',
    templateGroup: 'MONDIAL_2026_QUOTES',
    templateDescription: 'شريط تعريفي لشخصية أو لاعب أو محلل في تغطية مونديال 2026.',
    theme: { primaryColor: '#22d3ee', secondaryColor: '#0f172a', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      ...mondialCommonFields,
      { id: 'mondialVariant', label: 'نوع القالب', type: 'hidden', value: 'lower_third' },
      { id: 'personName', label: 'الاسم', type: 'text', value: 'أيمن حسين' },
      { id: 'personRole', label: 'الدور / الصفة', type: 'text', value: 'مهاجم — المنتخب العراقي' },
      { id: 'personFlag', label: 'إيموجي العلم', type: 'text', value: '🇮🇶' },
      { id: 'competitionTag', label: 'وسم البطولة', type: 'text', value: 'WC 2026' },
      { id: 'accentOverride', label: 'لون مخصص', type: 'color', value: '#22d3ee' },
    ],
  },
];

// ─── مجموعة 8: المنتخب العراقي 🇮🇶 ──────────────────────────────────────────

export const MONDIAL_IRAQ_TEMPLATES: OverlayConfig[] = [
  {
    id: 'template-mondial-iraq-squad',
    templateId: 'template-mondial-iraq-squad',
    name: '🇮🇶 العراق — بطاقة التشكيلة',
    type: OverlayType.MONDIAL_IRAQ,
    isVisible: false,
    templateIcon: '🇮🇶',
    templateAccent: '#007A3D',
    templateGroup: 'MONDIAL_2026_IRAQ',
    templateDescription: 'التشكيلة الرئيسية للمنتخب العراقي على ملعب مضيء بألوان العلم العراقي.',
    theme: { primaryColor: '#007A3D', secondaryColor: '#000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'channelName', label: 'اسم القناة', type: 'text', value: 'REO LIVE' },
      { id: 'iraqVariant', label: 'نوع القالب', type: 'hidden', value: 'squad_card' },
      { id: 'formation', label: 'التشكيلة', type: 'select', value: '4-3-3', options: [
        { value: '4-3-3', label: '4-3-3' },
        { value: '4-2-3-1', label: '4-2-3-1' },
        { value: '4-4-2', label: '4-4-2' },
        { value: '3-5-2', label: '3-5-2' },
        { value: '5-3-2', label: '5-3-2' },
      ]},
      { id: 'matchLabel', label: 'وصف المباراة', type: 'text', value: 'العراق vs الأرجنتين · المجموعة C' },
      { id: 'coachName', label: 'اسم المدرب', type: 'text', value: 'المدرب الوطني' },
      { id: 'squadJson', label: 'التشكيلة JSON', type: 'textarea', value: '[]' },
      { id: 'scale', label: 'الحجم', type: 'range', value: 1.0, min: 0.5, max: 1.8, step: 0.05 },
    ],
  },
  {
    id: 'template-mondial-iraq-player',
    templateId: 'template-mondial-iraq-player',
    name: '🇮🇶 العراق — تسليط الضوء على لاعب',
    type: OverlayType.MONDIAL_IRAQ,
    isVisible: false,
    templateIcon: '⭐',
    templateAccent: '#FFD700',
    templateGroup: 'MONDIAL_2026_IRAQ',
    templateDescription: 'بطاقة احتفالية بلاعب عراقي مع إحصائياته في المونديال واقتباسه.',
    theme: { primaryColor: '#007A3D', secondaryColor: '#000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'channelName', label: 'اسم القناة', type: 'text', value: 'REO LIVE' },
      { id: 'iraqVariant', label: 'نوع القالب', type: 'hidden', value: 'player_spotlight' },
      { id: 'playerName', label: 'اسم اللاعب', type: 'text', value: 'أيمن حسين' },
      { id: 'playerPosition', label: 'الموقع', type: 'text', value: 'مهاجم — قائد الهجوم' },
      { id: 'playerNumber', label: 'رقم القميص', type: 'text', value: '9' },
      { id: 'playerImage', label: 'صورة اللاعب', type: 'image', value: '' },
      { id: 'playerAge', label: 'العمر', type: 'text', value: '' },
      { id: 'playerClub', label: 'النادي', type: 'text', value: '' },
      { id: 'playerGoals', label: 'الأهداف في البطولة', type: 'number', value: 4 },
      { id: 'playerAssists', label: 'التمريرات الحاسمة', type: 'number', value: 1 },
      { id: 'playerRating', label: 'التقييم (0-10)', type: 'range', value: 8.8, min: 0, max: 10, step: 0.1 },
      { id: 'playerMatches', label: 'عدد المباريات', type: 'number', value: 4 },
      { id: 'playerQuote', label: 'اقتباس اللاعب', type: 'textarea', value: 'نحن هنا لنكتب التاريخ مع بلدنا الحبيب.' },
      { id: 'scale', label: 'الحجم', type: 'range', value: 1.0, min: 0.5, max: 1.8, step: 0.05 },
    ],
  },
  {
    id: 'template-mondial-iraq-ticker',
    templateId: 'template-mondial-iraq-ticker',
    name: '🇮🇶 العراق — شريط أخبار المنتخب',
    type: OverlayType.MONDIAL_IRAQ,
    isVisible: false,
    templateIcon: 'ITCK',
    templateAccent: '#C8102E',
    templateGroup: 'MONDIAL_2026_IRAQ',
    templateDescription: 'شريط متخصص بأخبار المنتخب العراقي مع إمكانية إظهار حالة المباراة الحية.',
    theme: { primaryColor: '#007A3D', secondaryColor: '#000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'channelName', label: 'اسم القناة', type: 'text', value: 'REO LIVE' },
      { id: 'iraqVariant', label: 'نوع القالب', type: 'hidden', value: 'match_ticker' },
      { id: 'iraqTickerLabel', label: 'عنوان الشريط', type: 'text', value: '🇮🇶 أخبار المنتخب العراقي' },
      { id: 'iraqNews', label: 'نص الشريط', type: 'textarea', value: 'العراق يتصدر المجموعة C — أيمن حسين يسجل الهدف الذهبي — جماهير عراقية تغزو ملاعب أمريكا' },
      { id: 'isLiveMatch', label: 'مباشر؟', type: 'boolean', value: true },
      { id: 'currentMatchInfo', label: 'معلومات المباراة الحية', type: 'text', value: 'العراق 1 : 0 الأرجنتين · ⏱️ 67\'' },
      { id: 'scrollSpeed', label: 'سرعة التمرير', type: 'range', value: 22, min: 5, max: 60, step: 1 },
    ],
  },
  {
    id: 'template-mondial-iraq-history',
    templateId: 'template-mondial-iraq-history',
    name: '🇮🇶 العراق — لحظة تاريخية',
    type: OverlayType.MONDIAL_IRAQ,
    isVisible: false,
    templateIcon: '📜',
    templateAccent: '#FFD700',
    templateGroup: 'MONDIAL_2026_IRAQ',
    templateDescription: 'قالب احتفالي للحظات التاريخية الكبيرة للمنتخب العراقي في المونديال.',
    theme: { primaryColor: '#007A3D', secondaryColor: '#000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'channelName', label: 'اسم القناة', type: 'text', value: 'REO LIVE' },
      { id: 'iraqVariant', label: 'نوع القالب', type: 'hidden', value: 'history_moment' },
      { id: 'momentTitle', label: 'عنوان اللحظة', type: 'text', value: 'لحظة تاريخية للعراق 🇮🇶' },
      { id: 'momentSubtitle', label: 'العنوان التوضيحي', type: 'text', value: 'أول تأهل عربي لثمن نهائي مونديال 2026!' },
      { id: 'momentDetails', label: 'تفاصيل اللحظة', type: 'textarea', value: 'كتب المنتخب العراقي اليوم صفحة ذهبية في تاريخ كرة القدم العربية.' },
      { id: 'momentYear', label: 'السنة', type: 'text', value: '2026' },
      { id: 'showHistory', label: 'إظهار السجل التاريخي', type: 'boolean', value: true },
      { id: 'scale', label: 'الحجم', type: 'range', value: 1.0, min: 0.5, max: 1.8, step: 0.05 },
    ],
  },
  {
    id: 'template-mondial-iraq-fan-pulse',
    templateId: 'template-mondial-iraq-fan-pulse',
    name: '🇮🇶 العراق — نبض الجماهير',
    type: OverlayType.MONDIAL_IRAQ,
    isVisible: false,
    templateIcon: '💚',
    templateAccent: '#007A3D',
    templateGroup: 'MONDIAL_2026_IRAQ',
    templateDescription: 'عداد جماهيري مع نسبة الدعم والهاشتاق وعدد المشاهدين الحيين.',
    theme: { primaryColor: '#007A3D', secondaryColor: '#000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'channelName', label: 'اسم القناة', type: 'text', value: 'REO LIVE' },
      { id: 'iraqVariant', label: 'نوع القالب', type: 'hidden', value: 'fan_pulse' },
      { id: 'fanCount', label: 'عدد المشجعين', type: 'text', value: '٤٢٫٥ مليون' },
      { id: 'countryRank', label: 'الترتيب', type: 'text', value: '#1 عربياً' },
      { id: 'pulseValue', label: 'نسبة الدعم %', type: 'range', value: 87, min: 0, max: 100, step: 1 },
      { id: 'hashTag', label: 'الهاشتاق', type: 'text', value: '#العراق_في_المونديال' },
      { id: 'liveViewers', label: 'المشاهدون الحيون', type: 'text', value: '1.2M مشاهد' },
      { id: 'supportMessage', label: 'رسالة الدعم', type: 'textarea', value: 'العراق يستحق. كل بيت عراقي يشجع.' },
      { id: 'isLive', label: 'وضع مباشر', type: 'boolean', value: true },
      { id: 'scale', label: 'الحجم', type: 'range', value: 1.0, min: 0.5, max: 1.8, step: 0.05 },
    ],
  },
  {
    id: 'template-mondial-iraq-dashboard',
    templateId: 'template-mondial-iraq-dashboard',
    name: '🇮🇶 العراق — لوحة معلومات المنتخب',
    type: OverlayType.MONDIAL_IRAQ,
    isVisible: false,
    templateIcon: 'DSH',
    templateAccent: '#007A3D',
    templateGroup: 'MONDIAL_2026_IRAQ',
    templateDescription: 'لوحة معلومات شاملة لمنتخب العراق تعرض الإحصائيات، نبض الجماهير، الترتيب والمباراة القادمة.',
    theme: { primaryColor: '#007A3D', secondaryColor: '#000', backgroundColor: 'transparent', fontFamily: 'Tajawal' },
    slots: {},
    fields: [
      { id: 'channelName', label: 'اسم القناة', type: 'text', value: 'REO LIVE' },
      { id: 'iraqVariant', label: 'نوع القالب', type: 'hidden', value: 'iraq_dashboard' },
      { id: 'title', label: 'العنوان الرئيسي', type: 'text', value: 'لوحة أداء أسود الرافدين' },
      { id: 'subtitle', label: 'العنوان الفرعي', type: 'text', value: 'تغطية خاصة وتحليلات لمنتخب العراق في كأس العالم 2026' },
      { id: 'points', label: 'النقاط', type: 'number', value: 4 },
      { id: 'goals', label: 'أهداف مسجلة', type: 'number', value: 5 },
      { id: 'conceded', label: 'أهداف مستقبلة', type: 'number', value: 3 },
      { id: 'wins', label: 'حالات الفوز', type: 'number', value: 1 },
      { id: 'pulseText', label: 'نبض الجماهير', type: 'textarea', value: 'تفاعل منقطع النظير في الشارع العراقي بعد الفوز التاريخي في الجولة السابقة. آلاف المشجعين يتأهبون لمؤازرة الأسود في لوس أنجلوس، وسط ثقة كبيرة من الشارع الرياضي في قدرة المدرب كاساس واللاعبين على حجز بطاقة العبور التاريخية للدور القادم.' },
      { id: 'groupLetter', label: 'رمز المجموعة', type: 'text', value: 'I' },
      { id: 'standingsJson', label: 'ترتيب المجموعة JSON', type: 'textarea', value: JSON.stringify([
        { rank: 1, code: 'FR', name: 'فرنسا', pts: 9 },
        { rank: 2, code: 'SN', name: 'السنغال', pts: 7 },
        { rank: 3, code: 'IQ', name: 'العراق', pts: 4 },
        { rank: 4, code: 'NO', name: 'النرويج', pts: 1 }
      ]) },
      { id: 'nextMatchJson', label: 'المباراة القادمة JSON', type: 'textarea', value: JSON.stringify({
        homeCode: 'IQ', homeName: 'العراق',
        awayCode: 'FR', awayName: 'فرنسا',
        time: '22:00', date: 'الإثنين 15 يونيو · لوس أنجلوس'
      }) },
      { id: 'scale', label: 'الحجم', type: 'range', value: 1.0, min: 0.5, max: 1.8, step: 0.05 },
    ],
  },
];

// ─── المصفوفة الكاملة ─────────────────────────────────────────────────────────

export const MONDIAL_2026_TEMPLATES: OverlayConfig[] = [
  ...MONDIAL_LIVE_TEMPLATES,
  ...MONDIAL_STATS_TEMPLATES,
  ...MONDIAL_RESULTS_TEMPLATES,
  ...MONDIAL_QUOTES_TEMPLATES,
  ...MONDIAL_ANALYSIS_TEMPLATES,
  ...MONDIAL_STARS_TEMPLATES,
  ...MONDIAL_NEWS_TEMPLATES,
  ...MONDIAL_IRAQ_TEMPLATES,
];

export default MONDIAL_2026_TEMPLATES;
